O3Args=(-O3 -pipe -ftree-vectorize )

case $1 in
arm64)
  export CROSSCC=aarch64-linux-gnu-gcc
  export CFLAGS="${O3Args[@]} march=armv8-a -mtune=generic -ftree-vectorize -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
  export LDFLAGS="Wl,-O3,--sort-common,--as-needed,-s"
  ;;
amd64|x86_64)
  export CROSSCC="x86_64-w64-mingw32-gcc"
  export CFLAGS="${O3Args[@]} -march=x86-64 -msse3 -mfpmath=sse -ftree-vectorize -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
  export LDFLAGS="Wl,-O3,--sort-common,--as-needed,-s"
  ;;
esac