O3Args=(-O3 -pipe -ftree-vectorize )

case $1 in
arm64|aarch64|armv8a)
  export CC="ccache aarch64-linux-gnu-gcc"
  export CFLAGS="${O3Args[@]} -march=armv8-a -mtune=generic -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
  export LDFLAGS="-Wl,-O3,--sort-common,--as-needed,-s"
  ;;
amd64|x86_64)
  export CC="ccache x86_64-linux-gnu-gcc"
  export CFLAGS="${O3Args[@]} -march=x86-64 -msse3 -mfpmath=sse -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
  export LDFLAGS="-Wl,-O3,--sort-common,--as-needed,-s"
  ;;
esac