O3Args=(-O3 -pipe -ftree-vectorize )

case $1 in
arm64|aarch64|armv8a)
  export CFLAGS="${O3Args[@]} -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
  export LDFLAGS="-s -Wl,--dynamic-linker=/data/data/com.winlator/files/imagefs/usr/lib/ld-linux-aarch64.so.1 -Wl,-rpath=/data/data/com.winlator/files/imagefs/usr/lib -Wl,--sort-common,--as-needed"
  ;;
amd64|x86_64)
  export CFLAGS="${O3Args[@]} -Wno-error=implicit-function-declaration -Wno-error=incompatible-pointer-types"
  export LDFLAGS="-s -Wl,--sort-common,--as-needed"
  ;;
esac