_patch_file_=(
fix-build_ffmpeg.patch
fix-build_opencl.patch
shutcutfix_proton.patch
../../winlator_10.10/0002-server-Change-paths-to-winlator-rootfs.patch
0003-nsiproxy-Implement-reading-interface-addresses-from-.fix.patch
../../winlator_10.10/0004-ntdll-Add-WINEARGS-env-to-append-extra-arguments.patch
../../winlator_10.10/0005-dinput-Implement-gamepad-device.patch
0006-xinput-Implement-gamepad-device.fix.patch
0007-winex11-Remove-XKeyboard-extension.fix.patch
../../winlator_10.10/0008-user32-Stretch-desktop-wallpaper.patch
../../winlator_10.10/0009-explorer-Add-icons-to-startmenu.patch
../../winlator_10.10/0010-win32u-Fix-text-offset-on-menu.patch
0011-shell32-Update-resources.fix.patch
../../winlator_10.10/0012-Update-startmenu-icons.patch
../../winlator_10.10/0014-winemenubuilder-Add-timeout-to-wait-for-parent-proce.patch
../../winlator_10.10/0015-dbghelp-Validate-process-handle.patch
../../winlator_10.10/0016-ntdll-Add-WINEVMEMMAXSIZE-env-to-limit-virtual-memor.patch
../../winlator_10.10/0017-ntdll-Add-WINEOVERRIDEAFFINITYMASK-env-to-override-p.patch
0018-user32-Update-icons.fix.patch
0019-comctl32-Update-icons.fix.patch
0020-inetcpl-Update-icons.fix.patch
../../winlator_10.10/0021-win32u-Force-change-display-settings-to-CDS_FULLSCRE.patch
../../winlator_10.10/0022-explorer-Add-nogui-option.patch
../../winlator_10.10/0023-ntdll-Add-WINVERSION-env-to-change-Windows-version.patch
0025-winebrowser-Always-open-win32-app-instead-of-native-.fix.patch
../../winlator_10.10/0027-Apply-ntdll-Syscall_Emulation-patch.patch
../../winlator_10.10/0028-mscoree-Show-Wine-Mono-Installer-if-not-found.patch
../../winlator_10.10/0029-appwiz-Add-fallback-URL-for-Wine-Mono-Gecko-installa.patch
../../winlator_10.10/0030-midimap-Implement-MIDI-Input-Output-over-socket.patch
../../winlator_10.10/0031-win32u-Do-not-duplicate-explorer.patch
../../winlator_10.10/0032-comdlg32-Add-New-Folder-button.patch
../../winlator_10.10/0033-dinput-Improve-gamepad-device-implementation.patch
../../winlator_10.10/0034-winex11-Do-not-use-additional-extensions-by-default.patch
0035-Remove-NtUserRegisterWindowMessage-implementation.fix.patch
0036-xinput-Improve-gamepad-device-implementation.fix.patch
../../winlator_10.10/0037-mmdevapi-Add-implementations-from-Wine-upstream.patch
../../winlator_10.10/0038-explorer-Fix-nogui-option.patch
../../winlator_10.10/0039-ntdll-Force-STATUS_SUCCESS-if-the-esync-and-server-o.patch
)