_patch_file_=(
  ../../wine-glibc/ori_10/add_gamepad.patch
  ../../wine-glibc/ori_10/desktop_Change_BitBlt_to_StretchBlt.patch
  ../../wine-glibc/ori_10/esync.patch
  ../../wine-glibc/ori_10/fsync.patch
  ../../wine-glibc/ori_10/load.patch
  ../../wine-glibc/ori_10/midimap_makefile.patch
  ../../wine-glibc/ori_10/path_fix_glibc.patch
  ../../wine-glibc/ori_10/virtual_Fix_address_space.patch
  ../../wine-glibc/ori_10/wine_virtual_memory.patch
  ../../wine-glibc/ori_10/xinput_dinput_makefile.patch
)