_patch_file_=(
  ori/add_gamepad.patch
  ori/desktop_Change_BitBlt_to_StretchBlt.patch
  ori/midimap_makefile.patch
  ori/path_fix_glibc.patch
  ori/xinput_dinput_makefile.patch
  midimap_10.15.patch
  x11drv_10.15.patch
  xinput_dinput_10.14.patch
  ../../wine_do_not_create_dxgi_device_manager2.patch
)
