_patch_file_=(
  ori/add_gamepad.patch
  ori/desktop_Change_BitBlt_to_StretchBlt.patch
  ori/esync_glibc.patch
  ori/fsync.patch
  ori/load.patch
  ori/path_fix_glibc.patch
  ori/preloader.patch
  ori/virtual_Fix_address_space.patch
  ori/wine_virtual_memory.patch
  ori/xinput_dinput_makefile.patch
  ori/midimap_makefile.patch
  midimap_10.15.patch
  x11drv_10.15.patch
  xinput_dinput_10.15.patch
)
