_patch_file_=(
  ../../wine-glibc/ori_10/add_gamepad.patch
  ../../wine-glibc/ori_10/desktop_Change_BitBlt_to_StretchBlt.patch
  ../../wine-glibc/ori_10/esync.patch
  ../../wine-glibc/ori_10/fsync.patch
  ../../wine-glibc/ori_10/load.patch
  ../../wine-glibc/ori_10/midimap_makefile.patch
  ../../wine-glibc/ori_10/path_fix_glibc.patch
  ../../wine-glibc/ori_10/xinput_dinput_makefile.patch
  ../../hangover/10.14/0002-wow64-Add-syscall-tracing.patch
  ../../hangover/10.14/0003-ntdll-Only-copy-LOWORD-of-x86-segments.patch
  ../../hangover/10.14/0004-ntdll-Force-all-wow64-host-allocations-outside-of-th.patch
  ../../hangover/10.14/0005-ntdll-Implement-WOW64-thread-suspension-helpers.patch
  ../../hangover/10.14/0006-wow64-Support-running-a-BT-module-provided-suspend-r.patch
  ../../hangover/10.14/0007-ntdll-Get-the-right-ImageBase-on-wow64.patch
  ../../hangover/10.14/0008-WIP-ntdll-ARM64EC-thread-suspension-support.patch
  ../../hangover/10.14/0009-wow64-Default-to-wowbox64-for-i386-emulation-but-all.patch
  ../../hangover/10.14/0010-ntdll-Default-to-libarm64ecfex-for-amd64-emulation.patch
  ../../hangover/10.14/0011-ntdll-Warn-when-running-on-page-sizes-other-than-4k.patch

)
#  ../../hangover/10.14/0012-Revert-configure-Properly-test-clang-for-dwarf-suppo.patch