_patch_file_=(
  ori/add_gamepad.patch
  ori/desktop_Change_BitBlt_to_StretchBlt.patch
  ori/load.patch
  ori/preloader.patch
  ori/virtual_Fix_address_space.patch
  ori/wine_virtual_memory.patch
  ori/xinput_dinput_makefile.patch
  ori/midimap_makefile.patch
  midimap_10.15.patch
  xinput_dinput_10.15.patch
  moze_path_fix.patch
  moze_esync.patch
  moze_fsync.patch
  ../../wine_do_not_create_dxgi_device_manager2.patch
)
