name: Compile Wine-TKG for Arm64ec (Glibc) (env BCC ubuntu)

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      sourceURL:
        description: "Wine Source URL"
        required: false
        default: ""
      llvmURL:
        description: "llvm mingw pack"
        required: false
        default: "https://github.com/mstorsjo/llvm-mingw/releases/download/20260324/llvm-mingw-20260324-ucrt-ubuntu-22.04-x86_64.tar.xz"
      targetBranch:
        description: "Wine Target Branch"
        required: false
        default: "wine-10.15-hangover"
      targetImagefs:
        description: "Fake Imagefs Environment, Download Package URL"
        required: false
        default: "https://github.com/moze30/rootfs-winlator-glibc/releases/download/rootfs-g7.1.5-1.1/imagefs-g7.1.5-1.1.tzst"
      customTag:
        description: "Custom Releases Tag"
        required: false
        default: "r"
      customDescription:
        description: "Custom Releases Description"
        required: false
        default: ""
      makeWineVK:
        description: "make wine vk (y/n)"
        required: false
        default: "y"

jobs:
  build_wine:
    runs-on: ubuntu-24.04
    name: Build Wine-TKG
    outputs:
      wineVer: ${{ steps.download.outputs.wineVer }}
    steps:
      - name: Pull Wine-TKG Source & Download BCC
        id: download
        run: |
          aria2c -s$(nproc) -x$(nproc) ${{ github.event.inputs.llvmURL }} || exit 1
          mkdir llvm_mingw
          tar --strip-components=1 -xvf *.tar.xz -C llvm_mingw/ && rm -rf *.tar.xz

          git clone --depth=1 https://github.com/Waim908/wine-winlator.git || exit 1

          wineSourceURL=${{ github.event.inputs.sourceURL }}
          [[ -z $wineSourceURL ]] && exit 1

          if [[ ! -z ${{ github.event.inputs.targetBranch }} ]]; then
            git clone --depth=1  -b ${{ github.event.inputs.targetBranch }} $wineSourceURL wine-src || exit 1
          else
            git clone --depth=1 $wineSourceURL wine-src || exit 1
          fi

          cd wine-src
          wineVer=$(echo ${{ github.event.inputs.targetBranch }} | sed 's/wine-//' | sed 's/-hangover//')
          echo "wineVer=$wineVer" >> $GITHUB_OUTPUT
          cd ..
          # aria2c -s16 -x16 https://github.com/Waim908/BCC/releases/download/wine-bcc-latest/wine-bcc.tar.xz || exit 1
          aria2c -s16 -x16 https://github.com/Waim908/BCC/releases/download/wine-arm64ec-ubuntu2404-bcc-latest/wine-ubuntu2404-bcc-arm64ec.tar.xz || exit 1
          tar xf *.tar.xz && rm -rf *.tar.xz

      - name: Setting BCC & Compile Wine-TKG
        run: |
          echo $(pwd)
          sudo bash wine-winlator/mount.sh mount ubuntu2404 || exit 1
          sudo cp -r -p wine-winlator/ ubuntu2404/tmp/
          sudo mv wine-src/ ubuntu2404/tmp/
          sudo mv llvm_mingw/ ubuntu2404/tmp/

      - name: Compile
        run: |
          sudo chroot ubuntu2404 bash -x /tmp/wine-winlator/ubuntu_arm64ec.sh ${{ steps.download.outputs.wineVer }} ${{ github.event.inputs.makeWineVK }} || exit 1
          sudo chmod 644 ubuntu2404/tmp/*.tar.xz

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build_arm64ec_wine
          path: /tmp/build_arm64ec_wine.tar.xz

  create_wcp:
    runs-on: ubuntu-24.04-arm
    container:
      image: ubuntu:24.04
      volumes:
        - /tmp:/tmp
      env:
        wineVer: ${{ needs.build_wine.outputs.wineVer }}
        wineTag: ${{ github.event.inputs.customTag }}
        targetImagefs: ${{ github.event.inputs.targetImagefs }}
    name: Create WCP Package
    needs: build_wine
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: build_arm64ec_wine
          path: /tmp/

      - name: Create WCP Package
        run: |
          if [[ -z $wineVer ]]; then
            echo "未定义wineVer!"
            exit 1
          else
            echo "wineVer: $wienVer"
          fi
          mkdir -p /data/data/com.winlator/files/imagefs
          apt update
          apt install -y patchelf 7zip aria2 zstd xz-utils locales
          echo "en_US.UTF-8" >> /etc/locale.gen
          locale-gen
          export LC_ALL=en_US.UTF-8
          aria2c -s16 -x16 $targetImagefs || exit 1
          tar xf *.tzst -C /data/data/com.winlator/files/imagefs/ && rm -rf *.tzst
          cd /tmp
          7z x build_arm64ec_wine.zip && rm -rf *.zip
          tar xvf *.tar.xz && rm -rf *.tar.xz
          aria2c https://raw.githubusercontent.com/Waim908/wine-winlator/main/wcp-package.sh || exit 1
          customDescription="${wineVer}-${wineTag}-arm64ec; Built form [https://github.com/Waim908/wine-winlator]" customWcpName=wine-${{ needs.build_wine.outputs.wineVer }}-arm64ec doNotCleanStaticLibrary=1 doNotFixLibrary=1 isArm64ec=1 bash -x wcp-package.sh /tmp/wine_build $wineVer || exit 1
          chmod 644 /tmp/output-wcp/*.wcp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build_wine.outputs.wineVer }}-${{ github.event.inputs.customTag }}-tkg-arm64ec
          name: Wine ${{ needs.build_wine.outputs.wineVer }} Arm64ec for Winlator Glibc (${{ github.event.inputs.customTag }})
          body: |
            自动编译版本。
            移植Proton MF
            启用Esync
            启用Fsync
            修改请查看此仓库源码。
            此版本请勿使用在cmod与Winlator Bionic分支，否则可能失败！
            Remake: ${{ github.event.inputs.customTag }}
            Update Description: ${{ github.event.inputs.customDescription }}

          files: /tmp/output-wcp/*.wcp
          draft: false
          prerelease: false
