name: Compile Wine-TKG for x86_64 (Glibc)

permissions:
  contents: write
  packages: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Wine-TKG Version"
        required: false
        default: "10.15"

env:
  wineVer: ${{ github.event.inputs.version }}

jobs:
  build_wine:
    runs-on: ubuntu-24.04
    name: Build Wine-TKG
    steps:
      - name: Download Cache
        id: cache-tag
        uses: actions/cache@v4
        with:
          path: /tmp/ccache.tar.xz
          key: tkg-ccache-amd64

      - name: Build Wine-TKG
        run: |
          [[ -z $wineVer ]] && { echo "你没有输入Wine版本！" && exit 1;}
          cd /tmp
          git clone --depth 1 https://github.com/Waim908/wine-winlator.git || exit 1
          git clone --depth 1 https://github.com/Frogging-Family/wine-tkg-git.git || exit 1

          echo "安装locales"
          sudo apt install -y locales-all || exit 1

          mkdir -p ~/.cache/
          if [[ -f /tmp/ccache.tar.xz ]]; then
            echo "找到Ccache缓存，正在解压..."
            tar -xf /tmp/ccache.tar.xz -C ~/.cache/ || exit 1
          else
            echo "未找到Ccache缓存，继续构建..."
          fi

          export ENABLE_PROTON_MF=1
          bash -x /tmp/wine-winlator/set-tkg-cfg.sh wine-$wineVer /tmp/wine-tkg-git/wine-tkg-git/

          bash +x /tmp/wine-winlator/add_patch.sh wine-glibc $wineVer /tmp/wine-tkg-git/wine-tkg-git/wine-tkg-userpatches/

          echo "正在构建Wine-TKG..."
          cd /tmp/wine-tkg-git/wine-tkg-git/
          echo '_ci_build="true"' >> customization.cfg
          yes | ./non-makepkg-build.sh || exit 1

          echo "正在保存Ccache缓存..."
          [[ -f /tmp/ccache.tar.xz ]] && rm -rf /tmp/ccache.tar.xz
          cd ~/.cache
          tar -I 'xz -T$(nproc) -9' -cf /tmp/ccache.tar.xz ccache || { cat /tmp/wine-tkg-git/wine-tkg-git/prepare.log  && exit 1;}

      - name: Save ccache
        uses: actions/cache/save@v5
        with:
          path: /tmp/ccache.tar.xz
          key: tkg-ccache-amd64

      - name: Package Wine-TKG
        run: |
          echo "正在打包Wine-TKG..."
          wine_path=$(ls /tmp/output/ 2>/dev/null)
          [[ -z $wine_path ]] && exit 1
          sudo bash -x /tmp/wine-winlator/wcp-package.sh /tmp/output/$wine_path $wineVer || exit 1



      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}-tkg
          name: Wine ${{ github.event.inputs.version }} TkG Staging GE for Winlator Glibc
          body: |
            自动编译版本。
            移植Proton MF
            启用Esync
            启用Fsync
            修改请查看此仓库源码。
          files: /tmp/output-wcp/*.wcp
          draft: false
          prerelease: false
